[project]
name = "src-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "aio-pika>=9.5.2",
    "profane-detector>=1.1.4",
    "psutil>=7.1.3",
    "spacy>=3.7.5",
    "uvloop>=0.21.0",
]
